### ISSUE TITLE
有输入框的Bug

### ISSUE THREAD

**Issue by Mase9527** [pujiaxin33/JXPopupView#4]
当View里面有输入框时 ，使用了IQBordManager ，输入框不会跟着键盘往上移

**Comment by pujiaxin33** [comment]
经过测试，如果不是被添加到window上面，IQKeyboardManager都是正常工作的。

如果在window上面显示，IQKeyboardManager是无法工作的。详情参考：[https://github.com/hackiftekhar/IQKeyboardManager/issues/1082](https://github.com/hackiftekhar/IQKeyboardManager/issues/1082)

>  Adding UITextField directly to UIWindow isn't supported by library, the textField must contain within a UIViewController
