### ISSUE TITLE
无法获取backgroundViewClicked回调方法

### ISSUE THREAD

**Issue by Channning** [pujiaxin33/JXPopupView#5]
不好意思，还是没明白如何调用didDismissCallback，来监听backgroundViewClicked然后dismiss回调，能不能给个示例？
let popupView = JXPopupView(containerView: containerView, contentView: contentView, animator: animator!)
        //配置交互
        popupView.isDismissible = true
        popupView.isInteractive = true
        //可以设置为false，再点击弹框中的button试试？
//        popupView.isInteractive = false
        popupView.isPenetrable = false
        //- 配置背景
        popupView.backgroundView.style = self.backgroundStyle
        popupView.backgroundView.blurEffectStyle = self.backgroundEffectStyle
        popupView.backgroundView.color = self.backgroundColor
        popupView.display(animated: true, completion: nil)
        
就比如你这个demo方法displayPopupView()，如何才能监听到由backgroundViewClicked触发的dismiss？不甚感谢！

**Comment by pujiaxin33** [comment]
我大概明白你想要的意思了，你只想要backgroundView点击导致的dismiss方法。但是目前没有，只是针对dismiss的回调。

**Comment by Channning** [comment]
我想通过这个方法dismiss(animated: Bool, completion: (()->())?)来监听backgroundView点击导致的dismiss，但是无法进入completion: (()->())?  这个现在是可以实现吗？

**Comment by pujiaxin33** [comment]
目前没有backgroundView点击导致的dismiss的回调方法

**Comment by pujiaxin33** [comment]
你可以自己给backgroundView添加一个event，比如`backgroundView.addTarget(self, action: #selector(backgroundViewClicked), for: .touchUpInside)`，这样你就能收到backgroundView的点击事情。
