### ISSUE TITLE
加在tableView上会随tableView滚动

### ISSUE THREAD

**Issue by deepindo** [pujiaxin33/JXPopupView#6]
作者好，一般常规的需求：如京东、美团等，是导航栏底部会有一行或者多行操作区域，里面不同的按钮会弹不同的框，这种为了效果，试过就只有加在tableView效果好一些，不过发现这个时间tableView滚动，不会收遮罩，弹框整体会随tableView滚动；
有些建议：
1. 框架可以加一个是否弹出的状态，如isPresent，这样一个是可以在多个按钮都会触发弹框的时候，做判断是否当然有弹出，可以先收起旧的弹框再弹出新的；
2. 关于前面加在tableView上会随着滚动，可以在scrollViewDidScoroll代理方法中也判断，有弹出，就一滚动就隐藏，但不能开启animated，不然遮罩隐藏效果会比较差，关掉animated还凑合，但是不够完美.

**Comment by pujiaxin33** [comment]
1、已经添加了isPresenting属性
2、按照你当前的方案是可行的。
