### ISSUE TITLE
Present时会消失，Dismiss后又显示，而不是一直显示

### ISSUE THREAD

**Issue by HelloHchen** [pujiaxin33/JXPopupView#8]
1、先在KeyWindow上显示一个Popup
2、获取TopController 来Present一个ControllerA
3、Dismiss  ControllerA

整个过程中，在2步时Popup会消失，3的时候又重新显示
理想状态下因该是  Present Dismiss都一直显示，Popup不会消失
这问题出现的原因是什么？

**Comment by pujiaxin33** [comment]
因为popup是通过addSubview的方式被添加到window中，然后再present 新的view controller，那么新加的view controller就会盖在popup上面。
